# Generated by Django 3.1.6 on 2021-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_users_amountadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='amountAdded',
        ),
        migrations.AddField(
            model_name='users',
            name='amountAdd',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
