# Generated by Django 3.1.6 on 2021-03-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210319_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='amountAdd',
            new_name='amountAdded',
        ),
    ]
