# Generated by Django 3.1.6 on 2021-03-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210319_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='amountAdded',
            field=models.IntegerField(),
        ),
    ]
