# Generated by Django 3.1.6 on 2021-03-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210319_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='amountAdded',
            new_name='amountAdd',
        ),
    ]
