# Generated by Django 3.1.6 on 2021-03-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210319_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='amountAdd',
            field=models.IntegerField(),
        ),
    ]
