# Generated by Django 3.1.6 on 2021-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210319_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='amountAdd',
            field=models.CharField(max_length=100),
        ),
    ]
