# Generated by Django 3.1.6 on 2021-02-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BankingSystem', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='depositers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositername', models.CharField(max_length=100)),
                ('depositeramount', models.IntegerField()),
                ('depositermobile', models.BigIntegerField()),
            ],
        ),
    ]
